version: "2"
services:
  ifsc:
    container_name: ifsc
    # restart: always
    build: ./backend
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "0.0.0.0:3003:3003"
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    # restart: always
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
